version: '3.8'

services:
  admin:
    build:
      context: .
      dockerfile: app_admin/Dockerfile
    container_name: admin-container
    volumes:
      - charm_keys:/app/keys
      - charm_users_keys:/app/users-keys
      - messages:/app/messages
    environment:
      - DISPLAY=host.docker.internal:0.0
    stdin_open: true
    tty: true
    command: python3 /app/src/app.py

  user:
    build:
      context: .
      dockerfile: app_user/Dockerfile
    container_name: user-container
    volumes:
      - charm_keys:/app/keys:ro       # en lecture seule si l'user ne doit pas écrire
      - charm_users_keys:/app/users-keys
      - messages:/app/messages
    environment:
      - DISPLAY=host.docker.internal:0.0
    stdin_open: true
    tty: true
    command: python3 /app/src/app.py

volumes:
  charm_keys:
  charm_users_keys:
  messages:
